In [1]:
import numpy as np

A = np.arange(1, 21).reshape(4, 5)
print("A=\n", A)
print("A dtype:", A.dtype)
print("A ndim:", A.ndim)
print("A shape:", A.shape)
print("A size:", A.size)
print("A itemsize:", A.itemsize)

B = A.reshape(5, 4)
print("\nB=\n", B)
print("B.shape:",B.shape)

A=
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
A dtype: int64
A ndim: 2
A shape: (4, 5)
A size: 20
A itemsize: 8

B=
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
B.shape: (5, 4)


In [2]:
import numpy as np
a = np.array([[0., 0., 0.],
              [10., 10., 10.],
              [20., 20., 20.],
              [30., 30., 30.]])
b = np.array([0., 1., 2.])

c = a + b
print("c=\n", c)

mask = (c >= 22)
print("\nMask=\n", mask)

count = mask.sum()
print("\nCount of values >= 22:", count)

c=
 [[ 0.  1.  2.]
 [10. 11. 12.]
 [20. 21. 22.]
 [30. 31. 32.]]

Mask=
 [[False False False]
 [False False False]
 [False False  True]
 [ True  True  True]]

Count of values >= 22: 4


In [3]:
grades = np.array([[87, 96, 70],
                   [100, 87, 90],
                   [94, 77, 90],
                   [100, 81, 82]])

overall_sum = np.sum(grades)
overall_min = np.min(grades)
overall_max = np.max(grades)
overall_mean = np.mean(grades)
overall_std = np.std(grades)
overall_var = np.var(grades)

print("Overall sum:", overall_sum)
print("Overall min:", overall_min)
print("Overall max:", overall_max)
print("Overall mean:", overall_mean)
print("Overall std:", overall_std)
print("Overall var:", overall_var)

mean_per_col = np.mean(grades, axis=0)
mean_per_row = np.mean(grades, axis=1)

print("Mean per column:", mean_per_col)
print("Mean per row:", mean_per_row)

max_per_row = np.max(grades, axis=1)
print("Max per row:", max_per_row)

Overall sum: 1054
Overall min: 70
Overall max: 100
Overall mean: 87.83333333333333
Overall std: 8.792357792739987
Overall var: 77.30555555555556
Mean per column: [95.25 85.25 83.  ]
Mean per row: [84.33333333 92.33333333 87.         87.66666667]
Max per row: [ 96 100  94 100]


In [4]:
import numpy as np
matrix = np.array([[2, 4, 6],
                   [1, 3, 5],
                   [7, 9, 11]])

sum_per_row = np.sum(matrix, axis=1)
sum_per_col = np.sum(matrix, axis=0)
overall_mean = np.mean(matrix)

print("Sum per row:", sum_per_row)
print("Sum per column:", sum_per_col)
print("Overall mean:", overall_mean)

Sum per row: [12  9 27]
Sum per column: [10 16 22]
Overall mean: 5.333333333333333


In [5]:
import numpy as np
A = np.array([[10, 20, 30],
              [40, 50, 60]])
B = np.array([1, 2, 3])

A_plus_B = A + B
A_times_2 = A * 2
A_minus_5 = A - 5


print("A + B:", A_plus_B)
print("A * 2:", A_times_2)
print("A - 5:", A_minus_5)

A + B: [[11 22 33]
 [41 52 63]]
A * 2: [[ 20  40  60]
 [ 80 100 120]]
A - 5: [[ 5 15 25]
 [35 45 55]]


In [6]:
import numpy as np
grades = np.array([[70, 85, 90],
                   [88, 76, 95],
                   [60, 80, 72]])

max_index = np.unravel_index(np.argmax(grades), grades.shape)
print("Index of max value:", max_index)

max_per_row_index = np.argmax(grades, axis=1)
print("Index of max per row:", max_per_row_index)

min_per_col_index = np.argmin(grades, axis=0)
print("Index of min per column:", min_per_col_index)

Index of max value: (np.int64(1), np.int64(2))
Index of max per row: [2 2 1]
Index of min per column: [2 1 2]


In [7]:
import numpy as np
def manhattan_distance(x1, y1, x2, y2):
    return abs(x2 - x1) + abs(y2 - y1)

def euclidean_distance(x1, y1, x2, y2):
    return np.sqrt((x2 - x1)**2 + (y2 - y1)**2)

# ex
p1, p2 = (1, 2), (4, 6)
print("Manhattan Distance:", manhattan_distance(p1[0], p1[1], p2[0], p2[1]))
print("Euclidean Distance:", euclidean_distance(p1[0], p1[1], p2[0], p2[1]))

Manhattan Distance: 7
Euclidean Distance: 5.0
